name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.17', '1.16' ]
    name: Go ${{ matrix.go }} test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Go stable version
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go }}
      - name: Test
        run: go test -v -race ./...
      - name: Upload code coverage to codecov
        if: matrix.go == '1.17'
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out

